services:
  chatbot:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - chatbot.env
    volumes:
      - ./documents:/documents
      - ./app/faiss:/app/faiss
      - ./model_cache:/root/.cache/huggingface
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  model_cache: